【Form】feat: 增加英文文档
DevCloudFE/vue-devui pull request #130
Opened 2022-01-01 06:47 UTC by AlanLee97

feat: 
- 增加英文文档

2022-01-02 13:05 UTC, kagol commented on packages/devui-vue/docs/en-US/components/form/index.md
> +```ty
```suggestion
```typescript
```

2022-01-02 13:14 UTC, AlanLee97 commented on packages/devui-vue/docs/en-US/components/form/index.md
> +```ty
> 

已改😆

2022-01-04 13:47 UTC, EditorWang requested changes
- feat 一般是新功能追加
- doc 一般是文档类的修改

2022-01-08 02:25 UTC, kagol approved these changes

2022-01-08 02:26 UTC, merged