refactor: Refactor code and component structure
DevCloudFE/vue-devui pull request #1475
Opened 2022-12-10 08:39 UTC by chenxi24

2022-12-12 08:40 UTC, GaoNeng-wWw requested changes
我做了一些拼写与翻译上的检查👍

2022-12-12 08:40 UTC, GaoNeng-wWw commented on packages/devui-vue/docs/en-US/components/editable-select/index.md
> +      <div>没有匹配项</div>
```suggestion
      <div>No matches</div>
```

2022-12-12 08:40 UTC, GaoNeng-wWw commented on packages/devui-vue/docs/en-US/components/editable-select/index.md
> +      <div>第{{ slotProps.index }}项: {{ slotProps.option.label }}</div>
```suggestion
      <div>Item {{ slotProps.index }}: {{ slotProps.option.label }}</div>
```

2022-12-13 01:33 UTC, chenxi24 commented on packages/devui-vue/docs/en-US/components/editable-select/index.md
> +      <div>第{{ slotProps.index }}项: {{ slotProps.option.label }}</div>
好的，马上改。

2022-12-16 11:44 UTC, GaoNeng-wWw approved these changes

2022-12-16 11:44 UTC, GaoNeng-wWw approved these changes

2022-12-16 11:45 UTC, GaoNeng-wWw approved these changes

2022-12-16 11:45 UTC, GaoNeng-wWw approved these changes

2022-12-16 11:47 UTC, GaoNeng-wWw approved these changes

2022-12-16 11:52 UTC, GaoNeng-wWw approved these changes

2022-12-16 12:08 UTC, GaoNeng-wWw commented
@chenxi24 

`The base branch requires all commits to be signed.`记得[为commit签名](https://cloud.tencent.com/developer/article/2111579)哦~，否则无法合并

2022-12-16 23:11 UTC, kagol commented
> @chenxi24
> 
> `The base branch requires all commits to be signed.`记得[为commit签名](https://cloud.tencent.com/developer/article/2111579)哦~，否则无法合并

可以参考下：https://insights.thoughtworks.cn/how-to-sign-git-commit/

2022-12-17 01:31 UTC, closed without merging