feat(Input): add input `validate-event` test case
DevCloudFE/vue-devui pull request #1570
Opened 2023-04-21 05:25 UTC by Wing-9527

add input `validate-event` test case

2023-04-21 08:02 UTC, GaoNeng-wWw requested changes

2023-04-21 09:40 UTC, Wing-9527 commented on packages/devui-vue/devui/input/__tests__/input.spec.ts
> +    // min length < 8
`const rules = { password: { min: 8, message: '密码至少8位', trigger: 'blur' } };`
我当时因为校验规则是这样，用`min`作为条件，所以注释就这样写了

2023-04-21 16:08 UTC, Wing-9527 commented
@kagol pls review

2023-04-22 05:33 UTC, GaoNeng-wWw approved these changes

2023-04-22 05:42 UTC, GaoNeng-wWw commented
@Wing-9527 还需要签名commit哦~

2023-04-22 05:46 UTC, GaoNeng-wWw commented
我会关闭掉这个PR，因为没有签名。请签名后重新开启一个新的PR，新的PR将会直接被approve并合并入库

2023-04-22 05:46 UTC, closed without merging